/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bjock1
 */
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class DogPoker extends javax.swing.JFrame {
    
    private Deck deck;
    private Player[] players = new Player[4];
    private Card[] board = new Card[5];
    private int pot = 0;
    private int toCall = 10;
    private int street = 0; //preflop 0, flop 1, turn 2, river 3
   
    private JLabel lblHole1, lblHole2; // your two hole card labels
    private JLabel[] communityCards = new JLabel[5]; // the 5 white boxes in the middle
    private JLabel lablToBet, lablFunds, lablPot; // side panel text
    private JLabel[] dogActions = new JLabel[3]; // where dogs say "Rex calls" etc.
    private JButton butnDeal, butnCall, butnFold; // buttons
    private JLabel lablRexFunds, lablLunaFunds, lablMaxFunds;
    private JLabel[] botFunds = new JLabel[3];
    private SoundPlayer bgMusic;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DogPoker.class.getName());

    /**
     * Creates new form DogPoker
     */
    public DogPoker() {
        initComponents();
        
        bgMusic = new SoundPlayer();
        bgMusic.play("/bg.wav",true);
        
        lblHole1 = HoleCard1;
        lblHole2 = HoleCard2;
       
        communityCards[0] = community1;
        communityCards[1] = community2;
        communityCards[2] = community3;
        communityCards[3] = community4;
        communityCards[4] = community5;
       
        dogActions[0] = lblDog1Action;
        dogActions[1] = lblDog2Action;
        dogActions[2] = lblDog3Action;
       
        lablToBet = lblToBet;
        lablFunds = lblFunds;
        lablPot = lblPot;
       
        butnDeal = btnDeal;
        butnCall = btnCall;
        butnFold = btnFold;
        
        lablRexFunds = lblRexFunds;
        lablLunaFunds = lblLunaFunds;
        lablMaxFunds = lblMaxFunds;
        
        botFunds[0] = lblRexFunds;
        botFunds[1] = lblLunaFunds;
        botFunds[2] = lblMaxFunds;
        
        players[0] = new HumanPlayer("YOU");
        players[1] = new BotPlayer("Rex");
        players[2] = new BotPlayer("Luna");
        players[3] = new BotPlayer("Max");
        
        for(int i=0;i<3;i++){
            botFunds[i].setText(players[i+1].getMoney() + "$");
        }
       
        for (Player p : players) p.win(100-p.getMoney());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Floor = new javax.swing.JPanel();
        PTable = new javax.swing.JPanel();
        CardOutline1 = new javax.swing.JPanel();
        community1 = new javax.swing.JLabel();
        CardOutline2 = new javax.swing.JPanel();
        community2 = new javax.swing.JLabel();
        CardOutline3 = new javax.swing.JPanel();
        community3 = new javax.swing.JLabel();
        CardOutline4 = new javax.swing.JPanel();
        community4 = new javax.swing.JLabel();
        CardOutline5 = new javax.swing.JPanel();
        community5 = new javax.swing.JLabel();
        MyCard1 = new javax.swing.JPanel();
        HoleCard1 = new javax.swing.JLabel();
        MyCard2 = new javax.swing.JPanel();
        HoleCard2 = new javax.swing.JLabel();
        btnDeal = new javax.swing.JButton();
        lblPot = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblToBet = new javax.swing.JLabel();
        lblYourBet = new javax.swing.JLabel();
        lblFunds = new javax.swing.JLabel();
        lblDog1Action = new javax.swing.JLabel();
        lblDog2Action = new javax.swing.JLabel();
        lblDog3Action = new javax.swing.JLabel();
        btnFold = new javax.swing.JButton();
        btnCall = new javax.swing.JButton();
        RexImg = new javax.swing.JLabel();
        LunaImg = new javax.swing.JLabel();
        MaxImg = new javax.swing.JLabel();
        lblLunaFunds = new javax.swing.JLabel();
        lblRexFunds = new javax.swing.JLabel();
        lblMaxFunds = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(200, 40, 30));
        setForeground(java.awt.Color.red);
        setResizable(false);

        Floor.setBackground(new java.awt.Color(140, 20, 30));
        Floor.setPreferredSize(new java.awt.Dimension(1200, 676));

        PTable.setBackground(new java.awt.Color(30, 120, 30));
        PTable.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 20, 20, 20, new java.awt.Color(102, 51, 0)));
        PTable.setPreferredSize(new java.awt.Dimension(738, 400));

        CardOutline1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        community1.setText("jLabel3");

        javax.swing.GroupLayout CardOutline1Layout = new javax.swing.GroupLayout(CardOutline1);
        CardOutline1.setLayout(CardOutline1Layout);
        CardOutline1Layout.setHorizontalGroup(
            CardOutline1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardOutline1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(community1))
        );
        CardOutline1Layout.setVerticalGroup(
            CardOutline1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardOutline1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(community1)
                .addGap(17, 17, 17))
        );

        CardOutline2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        community2.setText("jLabel3");

        javax.swing.GroupLayout CardOutline2Layout = new javax.swing.GroupLayout(CardOutline2);
        CardOutline2.setLayout(CardOutline2Layout);
        CardOutline2Layout.setHorizontalGroup(
            CardOutline2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardOutline2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(community2))
        );
        CardOutline2Layout.setVerticalGroup(
            CardOutline2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardOutline2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(community2)
                .addGap(15, 15, 15))
        );

        CardOutline3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        community3.setText("jLabel3");

        javax.swing.GroupLayout CardOutline3Layout = new javax.swing.GroupLayout(CardOutline3);
        CardOutline3.setLayout(CardOutline3Layout);
        CardOutline3Layout.setHorizontalGroup(
            CardOutline3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardOutline3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(community3))
        );
        CardOutline3Layout.setVerticalGroup(
            CardOutline3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardOutline3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(community3)
                .addGap(16, 16, 16))
        );

        CardOutline4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        community4.setText("jLabel3");

        javax.swing.GroupLayout CardOutline4Layout = new javax.swing.GroupLayout(CardOutline4);
        CardOutline4.setLayout(CardOutline4Layout);
        CardOutline4Layout.setHorizontalGroup(
            CardOutline4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardOutline4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(community4))
        );
        CardOutline4Layout.setVerticalGroup(
            CardOutline4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardOutline4Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(community4)
                .addGap(16, 16, 16))
        );

        CardOutline5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        community5.setText("jLabel3");

        javax.swing.GroupLayout CardOutline5Layout = new javax.swing.GroupLayout(CardOutline5);
        CardOutline5.setLayout(CardOutline5Layout);
        CardOutline5Layout.setHorizontalGroup(
            CardOutline5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardOutline5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(community5))
        );
        CardOutline5Layout.setVerticalGroup(
            CardOutline5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardOutline5Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(community5)
                .addGap(16, 16, 16))
        );

        MyCard1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        HoleCard1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HoleCard1.setText("jLabel3");

        javax.swing.GroupLayout MyCard1Layout = new javax.swing.GroupLayout(MyCard1);
        MyCard1.setLayout(MyCard1Layout);
        MyCard1Layout.setHorizontalGroup(
            MyCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyCard1Layout.createSequentialGroup()
                .addComponent(HoleCard1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MyCard1Layout.setVerticalGroup(
            MyCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyCard1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(HoleCard1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        MyCard2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        HoleCard2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HoleCard2.setText("jLabel4");

        javax.swing.GroupLayout MyCard2Layout = new javax.swing.GroupLayout(MyCard2);
        MyCard2.setLayout(MyCard2Layout);
        MyCard2Layout.setHorizontalGroup(
            MyCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyCard2Layout.createSequentialGroup()
                .addComponent(HoleCard2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MyCard2Layout.setVerticalGroup(
            MyCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyCard2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(HoleCard2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnDeal.setText("START");
        btnDeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDealActionPerformed(evt);
            }
        });

        lblPot.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPot.setForeground(new java.awt.Color(255, 255, 255));
        lblPot.setText("jLabel3");

        javax.swing.GroupLayout PTableLayout = new javax.swing.GroupLayout(PTable);
        PTable.setLayout(PTableLayout);
        PTableLayout.setHorizontalGroup(
            PTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTableLayout.createSequentialGroup()
                .addGroup(PTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PTableLayout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(MyCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MyCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PTableLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(PTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDeal)
                            .addGroup(PTableLayout.createSequentialGroup()
                                .addComponent(CardOutline1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CardOutline2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(CardOutline3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CardOutline4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CardOutline5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTableLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblPot)
                .addGap(309, 309, 309))
        );
        PTableLayout.setVerticalGroup(
            PTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTableLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(lblPot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CardOutline5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardOutline4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardOutline3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardOutline2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardOutline1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnDeal)
                .addGap(34, 34, 34)
                .addGroup(PTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MyCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MyCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblToBet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblToBet.setForeground(new java.awt.Color(255, 255, 255));
        lblToBet.setText("jLabel3");

        lblYourBet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblYourBet.setForeground(new java.awt.Color(255, 255, 255));
        lblYourBet.setText("jLabel3");

        lblFunds.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFunds.setForeground(new java.awt.Color(255, 255, 255));
        lblFunds.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFunds)
                    .addComponent(lblYourBet)
                    .addComponent(lblToBet))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblToBet)
                .addGap(37, 37, 37)
                .addComponent(lblYourBet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(lblFunds)
                .addGap(37, 37, 37))
        );

        lblDog1Action.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDog1Action.setForeground(new java.awt.Color(255, 255, 255));
        lblDog1Action.setText("jLabel3");

        lblDog2Action.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDog2Action.setForeground(new java.awt.Color(255, 255, 255));
        lblDog2Action.setText("jLabel3");

        lblDog3Action.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDog3Action.setForeground(new java.awt.Color(255, 255, 255));
        lblDog3Action.setText("jLabel3");

        btnFold.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFold.setText("FOLD");
        btnFold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoldActionPerformed(evt);
            }
        });

        btnCall.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCall.setText("CALL");
        btnCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCallActionPerformed(evt);
            }
        });

        RexImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RexImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rex.png"))); // NOI18N
        RexImg.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 51)));

        LunaImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LunaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Luna.png"))); // NOI18N
        LunaImg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 204), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 204), new java.awt.Color(51, 51, 255)));

        MaxImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MaxImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Max.png"))); // NOI18N
        MaxImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0)));

        lblLunaFunds.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLunaFunds.setForeground(new java.awt.Color(255, 255, 255));
        lblLunaFunds.setText("100$");

        lblRexFunds.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRexFunds.setForeground(new java.awt.Color(255, 255, 255));
        lblRexFunds.setText("100$");

        lblMaxFunds.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaxFunds.setForeground(new java.awt.Color(255, 255, 255));
        lblMaxFunds.setText("100$");

        javax.swing.GroupLayout FloorLayout = new javax.swing.GroupLayout(Floor);
        Floor.setLayout(FloorLayout);
        FloorLayout.setHorizontalGroup(
            FloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FloorLayout.createSequentialGroup()
                .addGroup(FloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FloorLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FloorLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(FloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FloorLayout.createSequentialGroup()
                                .addComponent(RexImg, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FloorLayout.createSequentialGroup()
                                .addGroup(FloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDog1Action)
                                    .addGroup(FloorLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblRexFunds)))
                                .addGap(81, 81, 81)))))
                .addGroup(FloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FloorLayout.createSequentialGroup()
                        .addComponent(PTable, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(FloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FloorLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(MaxImg))
                            .addGroup(FloorLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(FloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDog3Action)
                                    .addGroup(FloorLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblMaxFunds))))))
                    .addGroup(FloorLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnFold, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCall, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(151, 151, 151))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FloorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LunaImg)
                .addGap(69, 69, 69)
                .addGroup(FloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDog2Action)
                    .addComponent(lblLunaFunds))
                .addGap(513, 513, 513))
        );
        FloorLayout.setVerticalGroup(
            FloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FloorLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(FloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LunaImg)
                    .addGroup(FloorLayout.createSequentialGroup()
                        .addComponent(lblDog2Action)
                        .addGap(18, 18, 18)
                        .addComponent(lblLunaFunds)))
                .addGap(60, 60, 60)
                .addGroup(FloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(FloorLayout.createSequentialGroup()
                            .addComponent(PTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(FloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnFold, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                .addComponent(btnCall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(FloorLayout.createSequentialGroup()
                            .addComponent(RexImg)
                            .addGap(18, 18, 18)
                            .addComponent(lblDog1Action)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblRexFunds)
                            .addGap(49, 49, 49)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FloorLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(MaxImg, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDog3Action)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMaxFunds)))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Floor, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Floor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDealActionPerformed
        // TODO add your handling code here:
        deck = new Deck();
        pot = 0;
        toCall = 10;
        board = new Card[5];
        street = 0;
        
        for(Player p: players){
            p.resetForNewHand();
        }

        // Deal hole cards
        for (Player p : players) {
        p.receiveCard(deck.deal());
        p.receiveCard(deck.deal());
        }
        
        updateBotFunds();

        // Show your cards
        lblHole1.setText(players[0].getHoleCards().get(0).toString());
        lblHole2.setText(players[0].getHoleCards().get(1).toString());

        lblToBet.setText("To Bet: 10$");
        lblFunds.setText("Funds: $" + players[0].getMoney());
        lblPot.setText("Pot: $0");

        btnDeal.setEnabled(false);
        btnCall.setEnabled(true);
        btnFold.setEnabled(true);

        runBotActions();
       
        if (allBotsFolded()) {
            endHandUncontested();
        }
    }//GEN-LAST:event_btnDealActionPerformed

    private void btnCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCallActionPerformed
        // TODO add your handling code here:
        if (players[0].getMoney() < toCall) {
            players[0].fold();
        } else {
            players[0].pay(toCall);
        pot += toCall;
        lblPot.setText("Pot: $" + pot);
        lblFunds.setText("Funds: $" + players[0].getMoney());
        }
    advanceStreet();
    //checkGameOver();
    }//GEN-LAST:event_btnCallActionPerformed

    private void btnFoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoldActionPerformed
        // TODO add your handling code here:
        players[0].fold();
        advanceStreet();
    }//GEN-LAST:event_btnFoldActionPerformed

    private void advanceStreet() {
       btnCall.setEnabled(false);
btnFold.setEnabled(false);
street++;

if (street == 1) { // FLOP
    toCall = 20;
    lblToBet.setText("To Bet: $20");
    deck.burn();
    board[0] = deck.deal(); board[1] = deck.deal(); board[2] = deck.deal();
    communityCards[0].setText(board[0].toString());
    communityCards[1].setText(board[1].toString());
    communityCards[2].setText(board[2].toString());
    } else if (street == 2) { // TURN
        toCall = 30;
        lblToBet.setText("To Bet: $30");
        deck.burn();
        board[3] = deck.deal();
        communityCards[3].setText(board[3].toString());
    } else if (street == 3) { // RIVER
        toCall = 40;
        lblToBet.setText("To Bet: $40");
        deck.burn();
        board[4] = deck.deal();
        communityCards[4].setText(board[4].toString());
        } else { // SHOWDOWN
            showdown();
            return;
    }

    runBotActions();

    if (allBotsFolded()) {
        endHandUncontested();
    } else if (players[0].isInHand()) {
        btnCall.setEnabled(true);
        btnFold.setEnabled(true);
    } else {
        advanceStreet();
    }
}
    
     private void showdown() {
        int bestRank = 0;
        ArrayList<Player> winners = new ArrayList<>();

        for (Player p : players) {
            if (p.isInHand()) {
            int rank = HandEvaluator.evaluate(p, board);
            if (rank > bestRank) {
                bestRank = rank;
                winners.clear();
                winners.add(p);
                updateBotFunds();
            } else if (rank == bestRank) {
                winners.add(p);
                updateBotFunds();
            }
        }
    }

    int winAmount = pot / winners.size();
    for (Player w : winners) w.win(winAmount);

    JOptionPane.showMessageDialog(this, (winners.contains(players[0]) ? "You win $" + winAmount : "You lost. " + winners.get(0).getName() + " wins $" + winAmount) + " with " + HandEvaluator.handName(bestRank) + "!", "Showdown", JOptionPane.INFORMATION_MESSAGE);
    
    checkGameOver();
    replenishBotsIfNeeded();
    clearTable();
}
     
    private void runBotActions() {
        for (int i = 1; i < 4; i++) {
        Player bot = players[i];
       
        if (!bot.isInHand()) {
            dogActions[i-1].setText(bot.getName() + " already folded");
            continue;
        }

        int botMoney = bot.getMoney();

        if (botMoney >= toCall) {
            // Can afford full call
            boolean calls = bot.decideToCall(toCall, street == 0, board);
            if (calls) {
                bot.pay(toCall);
                pot += toCall;
                dogActions[i-1].setText(bot.getName() + " calls $" + toCall);
            } else {
                bot.fold();
                dogActions[i-1].setText(bot.getName() + " folds");
            }
        }
        else if (botMoney > 0) {
            // Can't afford full call → ALL-IN! AMERICAAAAAAAAAAAAAAAA
            pot += botMoney;
            bot.pay(botMoney);  // pays all remaining chips
            dogActions[i-1].setText(bot.getName() + " all-in $" + botMoney + "!");
            // They stay in hand automatically
        }
        else {
            // $0 → forced fold
            bot.fold();
            dogActions[i-1].setText(bot.getName() + " folds (broke)");
        }
    }

    lblPot.setText("Pot: $" + pot);
    updateBotFunds();  // gotta make sure da labels refresh
}

    private boolean allBotsFolded() {
        return !players[1].isInHand() && !players[2].isInHand() && !players[3].isInHand();
    }
   
    private void endHandUncontested() {
        players[0].win(pot);
        lblPot.setText("Pot: $0");
        lblFunds.setText("Funds: $" + players[0].getMoney());
        JOptionPane.showMessageDialog(this, "You win $" + pot + " uncontested! All dogs folded.", "Win", JOptionPane.INFORMATION_MESSAGE);
        updateBotFunds();
        checkGameOver();
        replenishBotsIfNeeded();
        clearTable();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DogPoker().setVisible(true));
    }
    
    private void clearTable() {
lblHole1.setText("");
lblHole2.setText("");
communityCards[0].setText("□□");
communityCards[1].setText("□□");
communityCards[2].setText("□□");
communityCards[3].setText("□□");
communityCards[4].setText("□□");
dogActions[0].setText("");
dogActions[1].setText("");
dogActions[2].setText("");
lblToBet.setText("To Bet:");
lblYourBet.setText("Your Bet:");
lblFunds.setText("Funds: $" + players[0].getMoney());
lblPot.setText("Pot: $0");
btnDeal.setEnabled(true);
btnCall.setEnabled(false);
btnFold.setEnabled(false);
}
    
    private void updateBotFunds(){
        for(int i=0;i<3;i++){
            botFunds[i].setText(players[i+1].getMoney() + "$");
        }
    }
    
    private void replenishBotsIfNeeded(){
        for(int i =0; i<4;i++){
            Player bot = players[i];
            
            if(bot.getMoney() <10){
                bot.win(100-bot.getMoney());
            }
        }
        updateBotFunds();
    }
    
    private void checkGameOver() {
        if (players[0].getMoney() <= 0) {
        // Human is broke → GAME OVER
        btnDeal.setEnabled(false);
        btnCall.setEnabled(false);
        btnFold.setEnabled(false);

        lblPot.setText("    GAME OVER");
        lblPot.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 48));
        lblPot.setForeground(new java.awt.Color(255, 50, 50)); // bright red

        lblFunds.setText("BUSTED: $0");
        lblFunds.setForeground(new java.awt.Color(255, 50, 50));

        JOptionPane.showMessageDialog(this, "You're out of money!\nAll the dogs win! Pls Close Window.\n\nFinal scores:\n" + players[1].getName() + ": $" + players[1].getMoney() + "\n" +players[2].getName() + ": $" + players[2].getMoney() + "\n" +players[3].getName() + ": $" + players[3].getMoney(),"Game Over – Dogs Win!",JOptionPane.WARNING_MESSAGE);
        bgMusic.stop();
        System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardOutline1;
    private javax.swing.JPanel CardOutline2;
    private javax.swing.JPanel CardOutline3;
    private javax.swing.JPanel CardOutline4;
    private javax.swing.JPanel CardOutline5;
    private javax.swing.JPanel Floor;
    private javax.swing.JLabel HoleCard1;
    private javax.swing.JLabel HoleCard2;
    private javax.swing.JLabel LunaImg;
    private javax.swing.JLabel MaxImg;
    private javax.swing.JPanel MyCard1;
    private javax.swing.JPanel MyCard2;
    private javax.swing.JPanel PTable;
    private javax.swing.JLabel RexImg;
    private javax.swing.JButton btnCall;
    private javax.swing.JButton btnDeal;
    private javax.swing.JButton btnFold;
    private javax.swing.JLabel community1;
    private javax.swing.JLabel community2;
    private javax.swing.JLabel community3;
    private javax.swing.JLabel community4;
    private javax.swing.JLabel community5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDog1Action;
    private javax.swing.JLabel lblDog2Action;
    private javax.swing.JLabel lblDog3Action;
    private javax.swing.JLabel lblFunds;
    private javax.swing.JLabel lblLunaFunds;
    private javax.swing.JLabel lblMaxFunds;
    private javax.swing.JLabel lblPot;
    private javax.swing.JLabel lblRexFunds;
    private javax.swing.JLabel lblToBet;
    private javax.swing.JLabel lblYourBet;
    // End of variables declaration//GEN-END:variables


}
